// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Check for missing keys immediately to aid debugging
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("__________________________________________________________");
  console.error("CRITICAL ERROR: MISSING SUPABASE ENVIRONMENT VARIABLES");
  console.error("VITE_SUPABASE_URL:", SUPABASE_URL ? "Set" : "MISSING");
  console.error("VITE_SUPABASE_ANON_KEY:", SUPABASE_ANON_KEY ? "Set" : "MISSING");
  console.error("Please add these to your Netlify Site Settings!");
  console.error("__________________________________________________________");
}

// Safer initialization that won't crash the entire app bundle if keys are missing
// This allows the UI to render and show a friendly error instead of a white screen
const createSafeClient = () => {
  try {
    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      throw new Error("Missing Supabase Credentials");
    }
    return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        storage: sessionStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (error) {
    console.error("Failed to initialize Supabase client:", error);

    // Return a structured dummy client that satisfies the AuthContext requirements
    // This prevents the "K.auth.onAuthStateChange is not a function" crash
    const mockClient = {
      auth: {
        getSession: () => Promise.resolve({ data: { session: null }, error: null }),
        getUser: () => Promise.resolve({ data: { user: null }, error: null }),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
        signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: "Supabase client not initialized. Missing environment variables." } }),
        signOut: () => Promise.resolve({ error: null }),
      },
      from: () => ({
        select: () => ({
          eq: () => ({
            limit: () => Promise.resolve({ data: null, error: { message: "Database not connected" } }),
            single: () => Promise.resolve({ data: null, error: { message: "Database not connected" } })
          })
        }),
        insert: () => Promise.resolve({ data: null, error: { message: "Database not connected" } }),
        update: () => Promise.resolve({ data: null, error: { message: "Database not connected" } }),
        delete: () => Promise.resolve({ data: null, error: { message: "Database not connected" } }),
      })
    };

    return mockClient as any;
  }
};

export const supabase = createSafeClient();